### ISSUE TITLE
Input module

### ISSUE THREAD

**Issue by GreatEmerald** [GreatEmerald/RGIC1601#1]
A module that reads an input raster and makes it available to other functions.

**Comment by GreatEmerald** [comment]
Basic implementation in commit https://github.com/GreatEmerald/RGIC1601/commit/be41f9d17cd0152a378c942f63c47e34c3fbc42d

**Comment by yyixiong** [comment]
I want task 1

**Comment by GreatEmerald** [comment]
Should be done now.
