### ISSUE TITLE
Errors upon importing GetOutliers.r

### ISSUE THREAD

**Issue by GreatEmerald** [GreatEmerald/RGIC1601#20]
When GetOutliers.r gets imported, R gives me these warnings and errors:

```
Error in list(nvars = 13L, ncases = 41, vname = c("linear", "diverging",  : 
  subscript out of bounds
Warning: failure to get object Kovesi
```

Would be nice to make sure this doesn't appear. Check if there are any packages that you are sourcing but are not actually used in the end.

**Comment by grathee** [comment]
it should now be sorted.
