### ISSUE TITLE
RasterToVector: NAs introduced by coercion

### ISSUE THREAD

**Issue by GreatEmerald** [GreatEmerald/RGIC1601#21]
When running the RasterToVector function, there is a warning in the output:

```
[1] "VI!"
Warning message:
In lapply(xd, as.numeric) : NAs introduced by coercion
```

This seems to be introduced by NAs in the input image that transfer over to the mean function within `lapply`.

**Comment by wschuc002** [comment]
This Warning message should not show after removing the 'spplot' line in the function.

**Comment by GreatEmerald** [comment]
Confirmed fixed.
