### ISSUE TITLE
RasterToVector: Make the VI raster layer optional

### ISSUE THREAD

**Issue by GreatEmerald** [GreatEmerald/RGIC1601#22]
The VI raster is only used for nicely colouring polygons. It should be optional, but currently it fails with the error:

```
Error in nbands(VIrast_in) : 
  argument "VIrast_in" is missing, with no default
```

**Comment by wschuc002** [comment]
This is probably solved now.

**Comment by GreatEmerald** [comment]
Confirmed fixed.
