### ISSUE TITLE
RasterToVector/util: Make use of fast rasterisation via GDAL

### ISSUE THREAD

**Issue by GreatEmerald** [GreatEmerald/RGIC1601#23]
The RasterToVector module should use the GDAL python script for fast rasterisation. However, it should also use rgdal's rasterToVector as a fallback, if the script is not found.

(I can try and take care of the util part myself, but feel free to take over if you'd like to do that)

**Comment by wschuc002** [comment]
Ready for testing.

**Comment by GreatEmerald** [comment]
Works, with a few things to iron out still.
