### ISSUE TITLE
Metadata create vs append

### ISSUE THREAD

**Issue by merijnslagter** [GreatEmerald/RGIC1601#26]
In GetComponent(), metadata is not appended but created.
The CalculateIndex() function also creates metadata and not appends it.

If CalculateIndex() comes earlier in sequence, I guess the GetComponent needs to be changed? 

https://github.com/GreatEmerald/RGIC1601/blob/master/backend/src/modules/GetComponent.r#L70

**Comment by GreatEmerald** [comment]
`CalculateIndex()` runs on the raw input image, not the component. So creating metadata in both modules is correct; RasterToVector is what then combines the metadata from both into one.
