### ISSUE TITLE
GetComponent: warnings during execution

### ISSUE THREAD

**Issue by GreatEmerald** [GreatEmerald/RGIC1601#29]
When running GetComponent on the base data, the output includes this warning message:

```
2: In princomp.default(na.omit(in_data), scale = T, center = T, retx = T) :
 extra arguments ‘scale’, ‘center’, ‘retx’ will be disregarded 
```

If this is fine, then it would be nice if the warning was suppressed. Otherwise, change what is necessary to avoid the warning.

**Comment by grathee** [comment]
Yeah! i had tried to work with different combinations of T or F but this warning seems to stay.
I can take another look but for now, I think this should not worry us.
