### ISSUE TITLE
GetOutliers

### ISSUE THREAD

**Issue by grathee** [GreatEmerald/RGIC1601#34]
the function create 8 levels of contour lines, and then chooses to use contour lines at level 5 to filter big enough polygons to find centroid from. However, the level 5 may not sometimes have any polygon. resultantly, output from gPolygonize is null and we can calculate garea from null and the function stops. 

May be we can polygonise all contour levels from 1 to 8 or 1 to say 6 and then find areas for each checking for the null input going in garea  and stopping the function. Then from there on we can set a threshold about the area of a polygon to find centroid from.

**Comment by wschuc002** [comment]
Good suggestion. If that does not work I could try to check if any polygons are created with 5 (default). In case there are no or too few polygons created: use level 6... and so on.

**Comment by wschuc002** [comment]
Could you test the updated version on the union field @grathee ?

**Comment by grathee** [comment]
on it!

**Comment by grathee** [comment]
solved!
