### ISSUE TITLE
GetOutliers module

### ISSUE THREAD

**Issue by GreatEmerald** [GreatEmerald/RGIC1601#5]
Module to find outliers from GetComponent module and return a point class.

**Comment by GreatEmerald** [comment]
Note that it doesn't need to read the files. The reading part is already done in Input(), so you can just use that for testing. The input parameter should be a RasterBrick/RasterStack, not a filename.

**Comment by wschuc002** [comment]
I see that the input will be a RasterLayer.
Module is ready for testing if I can get the input (= output GetComponent).

**Comment by GreatEmerald** [comment]
Yes, that's true. For now you can use `Input()[[1]]` for testing, that's the "cumulative" image (it's a RasterBrick, but with only one layer, so `[[1]]` should extract that).

**Comment by GreatEmerald** [comment]
Done, bugs/alternative implementations are discussed in issue #34.
